#  T-tests and P-values

In statistics, t-test is used to test if two data samples have a significant difference between their means. There are two types of t-test:

* **Student's t-test** (a.k.a. independent or uncorrelated t-test). This type of t-test is to compare the samples of **two independent populations** (e.g. test scores of students in two different classes). `scipy` provides the [`ttest_ind`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_ind.html) method to conduct student's t-test.

* **Paired t-test** (a.k.a. dependent or correlated t-test). This type of t-test is to compare the samples of **the same population** (e.g. scores of different tests of students in the same class). `scipy` provides the [`ttest_rel`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_rel.html) method to conduct paired t-test.

Both types of t-tests return a number which is called the **p-value**. If p-value is below 0.05, we can confidently declare the null-hypothesis is rejected and the difference is significant. If p-value is between 0.05 and 0.1, we may also declare the null-hypothesis is rejected but we are not highly confident. If p-value is above 0.1 we do not reject the null-hypothesis.

Read more about the t-test in [this article](http://b.link/test50) and [this Quora](http://b.link/unpaired97). Make sure you understand when to use which type of t-test.

In [45]:
# Import libraries
import pandas as pd
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import seaborn as sns

### One tailed t-test 
In a packing plant, a machine packs cartons with jars. It is supposed that a new machine will pack faster on the average than the machine currently used. To test that hypothesis, the times it takes each machine to pack ten cartons are recorded. The results, in seconds, are shown in the tables in the file files_for_lab/ttest_machine.xlsx. Assume that there is sufficient evidence to conduct the t test, does the data provide sufficient evidence to show if one machine is better than the other?

#### Import dataset

In [46]:
# Your code here:

data = pd.read_csv('ttest_machine.csv')

In [47]:
# H0 = The new machine has the same or slower average packing time as the old machine (>=)
# H1 = The new machine has a faster average packing time than the old machine (<)

In [48]:
t_stat, p_value_two_tailed = st.ttest_ind(data['New_machine'], data['Old_machine'], equal_var=False)

# Because of one tailed we need to devide the p value by 2

p_value_one_tailed = p_value_two_tailed / 2

print(f"""
t stat = {t_stat}
p value one tailed = {p_value_one_tailed}
      """)

t stat = -3.3972307061176026
p value one tailed = 0.00162112473315899

In [49]:
# A negative t-statistic indicates that the mean of the new machine's times is less than that of the old machine, which is in line with the alternative hypothesis. 
# The p-value is less than the commonly used significance level of 0.05, providing strong evidence against the null hypothesis.

#### Import dataset

In this challenge we will work on the Pokemon dataset you have already used. The goal is to test whether different groups of pokemon (e.g. Legendary vs Normal, Generation 1 vs 2, single-type vs dual-type) have different stats (e.g. HP, Attack, Defense, etc.). Use pokemon.csv

In [50]:
# Your code here:
pokemon = pd.read_csv("pokemon.csv")
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [51]:
s1_legendary = pokemon[pokemon['Legendary']==True].sample(50)
s2_non_legendary = pokemon[pokemon['Legendary']==False].sample(50)

#### First we want to define a function with which we can test the means of a feature set of two samples. 

In the next cell you'll see the annotations of the Python function that explains what this function does and its arguments and returned value. This type of annotation is called **docstring** which is a convention used among Python developers. The docstring convention allows developers to write consistent tech documentations for their codes so that others can read. It also allows some websites to automatically parse the docstrings and display user-friendly documentations.

Follow the specifications of the docstring and complete the function.

In [52]:
def t_test_features(s1, s2, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']):
    """Test means of a feature set of two samples
    
    Args:
        s1 (dataframe): sample 1
        s2 (dataframe): sample 2
        features (list): an array of features to test
    
    Returns:
        dict: a dictionary of t-test scores for each feature where the feature name is the key and the p-value is the value
    """
    results = {}

    for feature in features: 
        stat, p_val = st.ttest_ind(s1[feature], s2[feature], equal_var=False)
        results[feature] = p_val
    
    return results

#### Using the `t_test_features` function, conduct t-test for Lengendary vs non-Legendary pokemons.

*Hint: your output should look like below:*

```
{'HP': 1.0026911708035284e-13,
 'Attack': 2.520372449236646e-16,
 'Defense': 4.8269984949193316e-11,
 'Sp. Atk': 1.5514614112239812e-21,
 'Sp. Def': 2.2949327864052826e-15,
 'Speed': 1.049016311882451e-18,
 'Total': 9.357954335957446e-47}
 ```

In [53]:
# Your code here
t_test_results = t_test_features(s1_legendary, s2_non_legendary)
t_test_results

{'HP': 3.967749744607397e-09,
 'Attack': 1.9524292959908592e-13,
 'Defense': 1.1899226506773068e-07,
 'Sp. Atk': 5.793537278575513e-13,
 'Sp. Def': 5.8297261645461935e-12,
 'Speed': 9.56575433934279e-08,
 'Total': 2.1313634458982697e-25}

#### From the test results above, what conclusion can you make? Do Legendary and non-Legendary pokemons have significantly different stats on each feature?

In [54]:
# Your comment here

# H0: The stats are the same for legendary and non-legendary pokemons (=)
# H1: The stats are not the same for legendary and non_legendary pokemons (<>)

# There is strong evidence to conclude that Legendary and non-Legendary Pokémon have significantly different stats across all the tested features.

#### Next, conduct t-test for Generation 1 and Generation 2 pokemons.

In [66]:
# Your code here
s1_generation1 = pokemon[pokemon['Generation']==1]
s2_generation2 = pokemon[pokemon['Generation']==2]

display(s1_generation1)
display(s2_generation2)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,149,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
165,151,Mew,Psychic,NaN,600,100,100,100,100,100,100,1,False

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
166,152,Chikorita,Grass,NaN,318,45,49,65,49,65,45,2,False
167,153,Bayleef,Grass,NaN,405,60,62,80,63,80,60,2,False
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
169,155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,248,Tyranitar,Rock,Dark,600,100,134,110,95,100,61,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
269,249,Lugia,Psychic,Flying,680,106,90,130,90,154,110,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
271,251,Celebi,Psychic,Grass,600,100,100,100,100,100,100,2,False

In [56]:
t_test_results = t_test_features(s1_generation1, s2_generation2)
t_test_results

{'HP': 0.25853354975757525,
 'Attack': 0.04576528350446341,
 'Defense': 0.9540903014556121,
 'Sp. Atk': 0.2725816417116434,
 'Sp. Def': 0.7900709886600258,
 'Speed': 0.037516000110604734,
 'Total': 0.12241528711712697}

#### What conclusions can you make?

In [57]:
# Your comment here

# H0: The stats are the same for generation 1 and 2 pokemons (=)
# H1: The stats are not the same for generation 1 and 2 pokemons (<>)

# Most features do not show a significant difference between Pokémon from Generation 1 and Generation 2, except for Attack and Speed where the p-values are slightly below 0.05

#### Compare pokemons who have single type vs those having two types.

In [64]:
# Your code here
s1_type1 = pokemon[pokemon['Type 2'].isna()]
s2_type2 = pokemon[pokemon['Type 2'].notna()]

In [65]:
t_test_results = t_test_features(s1_type1, s2_type2)
t_test_results

{'HP': 0.11314389855379414,
 'Attack': 0.00014932578145948305,
 'Defense': 2.7978540411514693e-08,
 'Sp. Atk': 0.00013876216585667907,
 'Sp. Def': 0.00010730610934512779,
 'Speed': 0.02421703281819093,
 'Total': 1.1157056505229961e-07}

#### What conclusions can you make?

In [60]:
# Your comment here


# H0: The stats are the same for pokemons with single or those who have two types (=)
# H1: The stats are not the same for pokemons with single or those who have two types  (<>)

#  Except for HP, there is strong evidence to suggest that single-type and dual-type Pokémon have significantly different stats

#### Now, we want to compare whether there are significant differences of `Attack` vs `Defense`  and  `Sp. Atk` vs `Sp. Def` of all pokemons. Please write your code below.

*Hint: are you comparing different populations or the same population?*

In [61]:
# Your code here
def t_test_two_features(feature1, feature2, df):
    
    stat, p_val = st.ttest_rel(df[feature1], df[feature2])
    print(f"""
T-testing features: {feature1} and {feature2} 
Stat = {stat}
P_value = {p_val}
          """)
    
    return

In [62]:
t_test_two_features('Attack', 'Defense', pokemon)
t_test_two_features('Sp. Atk', 'Sp. Def', pokemon)

T-testing features: Attack and Defense
Stat = 4.325566393330478
P_value = 1.7140303479358558e-05


T-testing features: Sp. Atk and Sp. Def
Stat = 0.853986188453353
P_value = 0.3933685997548122

#### What conclusions can you make?

In [63]:
# Your comment here

# Attack and Defense
# H0: For all pokemons Attack and Defense Values are the same (=)
# H1: For all pokemons Attack and Defense Values are not the same  (<>)

# The p value is much almost 0 so we reject the 0 hypothesis, this indicates a significant difference between Attack and Defense stats for all Pokémon.



# Sp. Atk and Sp. Def
# H0: For all pokemons Sp. Atk and Sp. Def Values are the same (=)
# H1: For all pokemons Sp. Atk and Sp. Def Values are not the same  (<>)

# The p value is more than 0.05, this suggests that there is not enough evidence to conclude that special attack and special defense are significantly different for all Pokémon.